# Generated by Django 2.2.4 on 2019-09-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todopage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
