# Generated by Django 2.2.5 on 2019-09-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todopage', '0005_auto_20190924_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2019-09-26'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2019-09-26'),
        ),
    ]
